# Generated by Django 5.1.2 on 2024-11-01 21:10

import editor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "shortid",
                    models.CharField(editable=False, max_length=13, unique=True, verbose_name="short ID"),
                ),
                (
                    "longid",
                    models.CharField(editable=False, max_length=23, unique=True, verbose_name="long ID"),
                ),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("target", models.CharField(blank=True, max_length=255, verbose_name="target")),
                ("editor", models.CharField(blank=True, max_length=255, verbose_name="editor")),
                ("meta", models.JSONField(default=dict, verbose_name="meta")),
                ("content", editor.models.UniqueFileField(upload_to="projects", verbose_name="content")),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
