# Generated by Django 5.1.2 on 2024-11-01 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="time",
            new_name="created",
        ),
    ]
