# Generated by Django 5.1.2 on 2024-11-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0002_rename_time_project_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=200, verbose_name="description")),
                ("duration", models.PositiveIntegerField(blank=True, null=True, verbose_name="duration")),
                ("author", models.CharField(blank=True, max_length=50, verbose_name="author")),
                ("school", models.CharField(blank=True, max_length=100, verbose_name="school")),
                ("reviewed", models.BooleanField(default=False, verbose_name="reviewed")),
                ("approved", models.BooleanField(blank=True, null=True, verbose_name="approved")),
            ],
            options={
                "verbose_name": "submission",
                "verbose_name_plural": "submissions",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="editor",
            field=models.CharField(blank=True, max_length=50, verbose_name="editor"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="project",
            name="target",
            field=models.CharField(blank=True, max_length=50, verbose_name="target"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["shortid"], name="editor_proj_shortid_f0273c_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["longid"], name="editor_proj_longid_cafcb3_idx"),
        ),
        migrations.AddField(
            model_name="submission",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to="editor.project",
                verbose_name="project",
            ),
        ),
    ]
