# Generated by Django 5.1.2 on 2024-10-27 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patterns", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpattern",
            old_name="container",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="pattern",
            old_name="container",
            new_name="image",
        ),
    ]
