# Generated by Django 5.1.2 on 2024-10-31 19:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=50, unique=True, verbose_name="identifier")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
                ("source", models.URLField(blank=True, max_length=255, verbose_name="description")),
                ("docker", models.CharField(max_length=255, verbose_name="docker")),
                ("duration", models.PositiveIntegerField(blank=True, null=True, verbose_name="duration")),
                ("author", models.CharField(blank=True, max_length=255, verbose_name="author")),
                ("school", models.CharField(blank=True, max_length=255, verbose_name="school")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
            ],
            options={
                "verbose_name": "pattern",
                "verbose_name_plural": "patterns",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPattern",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("identifier", models.CharField(db_index=True, max_length=50, verbose_name="identifier")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
                ("docker", models.CharField(max_length=255, verbose_name="docker")),
                ("duration", models.IntegerField(blank=True, null=True, verbose_name="duration")),
                ("author", models.CharField(blank=True, max_length=255, verbose_name="author")),
                ("school", models.CharField(blank=True, max_length=255, verbose_name="school")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pattern",
                "verbose_name_plural": "historical patterns",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started", models.DateTimeField(blank=True, null=True, verbose_name="start time")),
                ("active", models.DateTimeField(blank=True, null=True, verbose_name="active time")),
                (
                    "pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="runner.pattern",
                        verbose_name="pattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "state",
            },
        ),
    ]
