# Generated by Django 5.1.2 on 2024-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0003_alter_historicalpattern_author_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pattern",
            index=models.Index(fields=["identifier"], name="runner_patt_identif_bd8375_idx"),
        ),
    ]
