# Generated by Django 5.1.2 on 2024-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0004_pattern_runner_patt_identif_bd8375_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpattern",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="visible"),
        ),
        migrations.AddField(
            model_name="pattern",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="visible"),
        ),
    ]
