# Generated by Django 5.1.2 on 2024-11-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0005_historicalpattern_visible_pattern_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("duration", models.PositiveIntegerField(default=60, verbose_name="default duration")),
            ],
            options={
                "verbose_name": "config",
            },
        ),
    ]
