# Generated by Django 5.1.3 on 2024-11-09 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0006_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pattern",
            options={
                "ordering": ["identifier"],
                "verbose_name": "pattern",
                "verbose_name_plural": "patterns",
            },
        ),
    ]
