# Generated by Django 5.1.3 on 2024-11-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runner", "0007_alter_pattern_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="config",
            old_name="duration",
            new_name="default_duration",
        ),
        migrations.RemoveField(
            model_name="state",
            name="active",
        ),
        migrations.RemoveField(
            model_name="state",
            name="pattern",
        ),
        migrations.RemoveField(
            model_name="state",
            name="started",
        ),
        migrations.AddField(
            model_name="state",
            name="current_pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="runner.pattern",
                verbose_name="current pattern",
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="current_pattern_started",
            field=models.DateTimeField(blank=True, null=True, verbose_name="current pattern started"),
        ),
        migrations.AddField(
            model_name="state",
            name="runner_last_active",
            field=models.DateTimeField(blank=True, null=True, verbose_name="runner last active"),
        ),
    ]
